# Generated by Django 5.2.3 on 2025-06-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0007_alter_arduinodata_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignmentsuserdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('college_role', models.CharField(max_length=100)),
                ('feild_key', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='dbnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='kisandata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Farmer', 'Farmer'), ('Buyer', 'Buyer')], max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('no_of_acres', models.CharField(blank=True, max_length=20, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('has_equipment', models.BooleanField(default=False)),
                ('pricing_per_hour', models.CharField(blank=True, max_length=20, null=True)),
                ('pricing_per_day', models.CharField(blank=True, max_length=20, null=True)),
                ('pricing_per_week', models.CharField(blank=True, max_length=20, null=True)),
                ('pricing_per_month', models.CharField(blank=True, max_length=20, null=True)),
                ('pricing_per_acre', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daysandassignments',
            name='assignments',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='daysandassignments',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='userdata',
            field=models.CharField(max_length=50000),
        ),
        migrations.CreateModel(
            name='dbnOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='firstdemoapp2.dbnorder')),
            ],
        ),
    ]
