# Generated by Django 5.2.3 on 2025-06-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0008_assignmentsuserdata_dbnorder_kisandata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=100)),
                ('game_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsNotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsDailyActivityImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='firstdemoapp2.sportsdailyactivity')),
            ],
        ),
    ]
