# Generated by Django 5.2.3 on 2025-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0009_sportsdailyactivity_sportsnotificationtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsuserdata',
            name='approval',
            field=models.BooleanField(),
        ),
    ]
