# Generated by Django 5.2.3 on 2025-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0010_alter_assignmentsuserdata_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsuserdata',
            name='approval',
            field=models.BooleanField(default=True),
        ),
    ]
