# Generated by Django 5.2.3 on 2025-07-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0011_alter_assignmentsuserdata_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('no_of_acres', models.CharField(max_length=50)),
                ('crop_type', models.CharField(max_length=100)),
                ('has_equipment', models.BooleanField(default=False)),
                ('equipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_description', models.TextField(blank=True, null=True)),
                ('pricing_per_hour', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing_per_day', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing_per_week', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing_per_month', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing_per_acre', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(max_length=50)),
                ('has_crops', models.BooleanField(default=False)),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_type_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('equipment_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
