# Generated by Django 5.2.3 on 2025-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0012_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=10)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('steps', models.IntegerField()),
                ('sleep_hours', models.FloatField()),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_time', models.CharField(max_length=50)),
                ('medicine_status', models.CharField(default='Pending', max_length=20)),
                ('appointments', models.JSONField(default=list)),
            ],
        ),
    ]
