# Generated by Django 5.2.3 on 2025-10-10 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0013_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('soil_moisture_level', models.CharField(max_length=50)),
                ('soil_value', models.IntegerField()),
                ('turbidity_level', models.CharField(max_length=50)),
                ('turbidity_value', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
